### PR TITLE
Fix TalonFX Closed Loop Ref and Sim Gearing

### LINKED ISSUE #92: Fix TalonFX Closed Loop Ref and Sim Gearing
Fixing sim gearing issue, and not publishing closed loop ref if using dynamic MM

### PR DESCRIPTION
**Pull request by Spybh66**
fixed sim gearing, control type check for pos control and mm control

### CODE REVIEW

**Comment by Spybh66** [comment]
Closes #92

File: src/main/java/frc/lib/io/motor/MotorIOTalonFXSim.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ public MotorIOTalonFXSim(String name, TalonFXConfiguration config, CAN main,
     @Override
     public void setPosition(Angle position)
     {
-        simState.setRawRotorPosition(position.div(gearRatio));
+        simState.setRawRotorPosition(position.times(gearRatio));
```
Comment (CJendantix) [inline src/main/java/frc/lib/io/motor/MotorIOTalonFXSim.java:58]: Wasn't sure about this myself, thanks

File: src/main/java/frc/lib/io/motor/MotorIOTalonFX.java [hunk 2]
```diff
@@ -156,6 +156,7 @@ protected boolean isRunningPositionControl()
         return (control instanceof PositionTorqueCurrentFOC)
             || (control instanceof PositionVoltage)
             || (control instanceof MotionMagicTorqueCurrentFOC)
+            || (control instanceof DynamicMotionMagicTorqueCurrentFOC)
```
Comment (CJendantix) [inline src/main/java/frc/lib/io/motor/MotorIOTalonFX.java:159]: Forgot about that

**Review by CJendantix — APPROVED** [review]

**Review by jw00541 — COMMENTED** [review]
Seems fine
