### PR TITLE
Fix MotorIO

### LINKED ISSUE #234: Fix Motor IO Layers to improve replay compatibility
I've noticed a couple issues with my original implementation

a. I set values to null, this is not compatible with `AutoLogged`
b. I have getter methods in `MotorIO`, these return garbage values in replay

### PR DESCRIPTION
**Pull request by CJendantix**
Resolved #234

### CODE REVIEW

**Review by Spybh66 — APPROVED** [review]

File: src/main/java/frc/lib/io/motor/MotorIOTalonFX.java [hunk 1]
```diff
@@ -93,7 +89,6 @@ public record TalonFXFollower(Device.CAN id, boolean opposesMain) {
     public MotorIOTalonFX(String name, TalonFXConfiguration config, Device.CAN main,
```
Comment (Nosh-H) [inline src/main/java/frc/lib/io/motor/MotorIOTalonFX.java:89]: Do you still need name as a parameter here, as it's being moved to the mechanisms?
